// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('ant-design-vue/es')['Avatar']
    AButton: typeof import('ant-design-vue/es')['Button']
    ADropdown: typeof import('ant-design-vue/es')['Dropdown']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    GridItem: typeof import('vue3-grid-layout')['GridItem']
    GridLayout: typeof import('vue3-grid-layout')['GridLayout']
    IBxsMessageSquareDots: typeof import('~icons/bxs/message-square-dots')['default']
    IBxVideoRecording: typeof import('~icons/bx/video-recording')['default']
    IFluentCallEnd16Filled: typeof import('~icons/fluent/call-end16-filled')['default']
    IIcRoundMic: typeof import('~icons/ic/round-mic')['default']
    IIcRoundVideocam: typeof import('~icons/ic/round-videocam')['default']
    IIonVideocam: typeof import('~icons/ion/videocam')['default']
    IIonVideocamOff: typeof import('~icons/ion/videocam-off')['default']
    IMajesticonsUsers: typeof import('~icons/majesticons/users')['default']
    IMaterialSymbolsAdminPanelSettings: typeof import('~icons/material-symbols/admin-panel-settings')['default']
    IMaterialSymbolsAndroidContacts: typeof import('~icons/material-symbols/android-contacts')['default']
    IMdiMicrophoneOff: typeof import('~icons/mdi/microphone-off')['default']
    InviteMember: typeof import('./../src/components/room/InviteMember.vue')['default']
    InviteMemberItem: typeof import('@components/room/InviteMember.vue')['default']
    IPhDotsThreeOutlineVerticalFill: typeof import('~icons/ph/dots-three-outline-vertical-fill')['default']
    ITypcnUserAdd: typeof import('~icons/typcn/user-add')['default']
    MasterLayout: typeof import('./../src/components/includes/MasterLayout.vue')['default']
    MediaItem: typeof import('./../src/components/room/MediaItem.vue')['default']
    RoomBody: typeof import('./../src/components/room/RoomBody.vue')['default']
    RoomConfirm: typeof import('./../src/components/room/RoomConfirm.vue')['default']
    RoomContent: typeof import('./../src/components/room/RoomContent.vue')['default']
    RoomFooter: typeof import('./../src/components/room/RoomFooter.vue')['default']
    RoomHead: typeof import('./../src/components/room/RoomHead.vue')['default']
    RoomLayout: typeof import('./../src/components/room/RoomLayout.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
